spring:
  application:
    name: btg-funds-platform-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password123@localhost:27017/btgfunds_db?authSource=admin}
  autoconfigure:
    exclude: []

server:
  port: 8081
  shutdown: graceful
  life-cycle:
    timeout: 20s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:}
    clients-table: ${DYNAMODB_CLIENTS_TABLE:Clients}
    funds-table: ${DYNAMODB_FUNDS_TABLE:Funds}
    transactions-table: ${DYNAMODB_TRANSACTIONS_TABLE:Transactions}
  ses:
    sender-email: ${AWS_SES_SENDER_EMAIL:noreply@btgfunds.com}

logging:
  level:
    com.btg.funds: DEBUG

---
spring:
  config:
    activate:
      on-profile: "!aws"
aws:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}

---
spring:
  config:
    activate:
      on-profile: aws
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
